//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.TaskReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskReference.ITaskService")]
    public interface ITaskService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/GetTaskTitle", ReplyAction="http://tempuri.org/ITaskService/GetTaskTitleResponse")]
        string GetTaskTitle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/GetTaskTitle", ReplyAction="http://tempuri.org/ITaskService/GetTaskTitleResponse")]
        System.Threading.Tasks.Task<string> GetTaskTitleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/SetTaskTitle", ReplyAction="http://tempuri.org/ITaskService/SetTaskTitleResponse")]
        void SetTaskTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/SetTaskTitle", ReplyAction="http://tempuri.org/ITaskService/SetTaskTitleResponse")]
        System.Threading.Tasks.Task SetTaskTitleAsync(string title);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskServiceChannel : TestConsole.TaskReference.ITaskService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskServiceClient : System.ServiceModel.ClientBase<TestConsole.TaskReference.ITaskService>, TestConsole.TaskReference.ITaskService {
        
        public TaskServiceClient() {
        }
        
        public TaskServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTaskTitle() {
            return base.Channel.GetTaskTitle();
        }
        
        public System.Threading.Tasks.Task<string> GetTaskTitleAsync() {
            return base.Channel.GetTaskTitleAsync();
        }
        
        public void SetTaskTitle(string title) {
            base.Channel.SetTaskTitle(title);
        }
        
        public System.Threading.Tasks.Task SetTaskTitleAsync(string title) {
            return base.Channel.SetTaskTitleAsync(title);
        }
    }
}
